webtalk_init -webtalk_dir F:/Thiet_ke_he_thong_so/thuchanh/bodem_bcd_30/bodem_bcd_30.sim/sim_1/behav/xsim/xsim.dir/cnt10tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Mar 15 21:33:58 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "212387440_0_0_902" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "e0680974-bbec-4c2c-a1b8-67d278446e84" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "8025a491a1b447b58f68217cc6350b58" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "64" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2304 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "12.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6764_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2743896050 -regid "212387440_0_0_902" -xml F:/Thiet_ke_he_thong_so/thuchanh/bodem_bcd_30/bodem_bcd_30.sim/sim_1/behav/xsim/xsim.dir/cnt10tb_behav/webtalk/usage_statistics_ext_xsim.xml -html F:/Thiet_ke_he_thong_so/thuchanh/bodem_bcd_30/bodem_bcd_30.sim/sim_1/behav/xsim/xsim.dir/cnt10tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm F:/Thiet_ke_he_thong_so/thuchanh/bodem_bcd_30/bodem_bcd_30.sim/sim_1/behav/xsim/xsim.dir/cnt10tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
